on: workflow_call
jobs:     
  ci:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v5

    - name: setup
      run: |
        corepack enable
        corepack prepare --activate

    - name: restore
      run: |
        pnpm i --frozen-lockfile

    - name: build
      run: |
        pnpm -r build

    - name: test
      run: |
        pnpm -r test

    - name: rewrite package readme assets
      if: ${{ github.event_name == 'pull_request' && startsWith(github.base_ref, 'release') }}
      uses: svs-tm/ci-cd/.github/actions/rewrite-package-readme-assets@main
      with:
        path: ${{ github.workspace }}
        commit: ${{ github.sha }}

    - name: pack
      if: ${{ github.event_name == 'pull_request' && startsWith(github.base_ref, 'release') }}
      run: |
        pnpm -r pack
  
    - name: publish artifact
      if: ${{ github.event_name == 'pull_request' && startsWith(github.base_ref, 'release') }}
      uses: actions/upload-artifact@v5
      with:
        name: ${{ github.event.pull_request.id }}
        path: |
            ${{ github.workspace }}/**/*.tgz
            ${{ github.workspace }}/**/coverage/**
            ${{ github.workspace }}/**/test-results/**
            !${{ github.workspace }}/**/node_modules/**
        overwrite: true
        retention-days: 7
